/********************************************
* This is a configuration file generated by
* Processor Expert for the MemManager module.
********************************************/

#ifndef _MEM_MANAGER_CONFIG_H_
#define _MEM_MANAGER_CONFIG_H_

/*Defines pools by block size and number of blocks. Must be aligned to 4 bytes.*/
#ifndef PoolsDetails_c
#define PoolsDetails_c \
         _block_size_  64  _number_of_blocks_    8 _eol_  \
         _block_size_ 128  _number_of_blocks_    2 _eol_  \
         _block_size_ 320  _number_of_blocks_    6 _eol_
#endif

/*Enables debug features: tracking and statistics.*/
/*Tracking disabled*/
/*Statistics disabled*/

#endif //_MEM_MANAGER_CONFIG_H_
