/********************************************
* This is a configuration file generated by
* Processor Expert for the SerialManager module.
********************************************/

#ifndef _SERIALMANAGER_CONFIG_H_
#define _SERIALMANAGER_CONFIG_H_

#ifndef gSerialMgr_ParamValidation_d
#define gSerialMgr_ParamValidation_d 1
#endif
#ifndef gSerialMgr_BlockSenderOnQueueFull_c
#define gSerialMgr_BlockSenderOnQueueFull_c 1
#endif
#ifndef gSerialManagerMaxInterfaces_c
#define gSerialManagerMaxInterfaces_c 1
#endif
#ifndef gSerialMgrUseUartA_c
#define gSerialMgrUseUartA_c 1
#endif
#ifndef gSerialMgrUseUartB_c
#define gSerialMgrUseUartB_c 0
#endif
#ifndef gSerialMgrUseUSB_c
#define gSerialMgrUseUSB_c 0
#endif
#ifndef gSerialMgrUseIIC_c
#define gSerialMgrUseIIC_c 0
#endif
#ifndef gSerialMgrUseSPI_c
#define gSerialMgrUseSPI_c 0
#endif
#ifndef gSerialMgrIICAddress_c
#define gSerialMgrIICAddress_c 0x76
#endif
#ifndef gSerialMgrRxBufSize_c
#define gSerialMgrRxBufSize_c 64
#endif
#ifndef gSerialMgrTxQueueSize_c
#define gSerialMgrTxQueueSize_c 10
#endif
#ifndef gSerialTaskStackSize_c
#define gSerialTaskStackSize_c 700
#endif
#ifndef gSerialTaskPriority_c
#define gSerialTaskPriority_c osPriorityBelowNormal
#endif

#endif //_SERIALMANAGER_CONFIG_H_
