/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : DataAvailablePin.c
**     Project     : ProcessorExpert
**     Processor   : MKL26Z128VLL4
**     Component   : GPIO_LDD
**     Version     : Component 01.128, Driver 01.08, CPU db: 3.00.000
**     Compiler    : IAR ARM C Compiler
**     Date/Time   : 2014-10-10, 12:09, # CodeGen: 152
**     Abstract    :
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
**     Settings    :
**          Component name                                 : DataAvailablePin
**          Port                                           : PTD
**          Port width                                     : 32 bits
**          Mask of allocated pins                         : 2
**          Interrupt service/event                        : Enabled
**            Interrupt                                    : INT_PORTC_PORTD
**            Interrupt priority                           : medium priority
**          Bit fields                                     : 1
**            Bit field                                    :
**              Field name                                 : DAP
**              Pins                                       : 1
**                Pin                                      :
**                  Pin                                    : ADC0_SE5b/PTD1/SPI0_SCK/TPM0_CH1
**                  Pin signal                             :
**                  Initial pin direction                  : Input
**                  Initial pin event                      : Disabled
**          Initialization                                 :
**            Auto initialization                          : no
**            Event mask                                   :
**              OnPortEvent                                : Enabled
**     Contents    :
**         Init                   - LDD_TDeviceData* DataAvailablePin_Init(LDD_TUserData *UserDataPtr);
**         SetPortEventCondition  - LDD_TError DataAvailablePin_SetPortEventCondition(LDD_TDeviceData...
**         SetPortInputDirection  - void DataAvailablePin_SetPortInputDirection(LDD_TDeviceData *DeviceDataPtr,...
**         SetPortOutputDirection - void DataAvailablePin_SetPortOutputDirection(LDD_TDeviceData *DeviceDataPtr,...
**         GetFieldValue          - DataAvailablePin_TFieldValue DataAvailablePin_GetFieldValue(LDD_TDeviceData...
**         ClearFieldBits         - void DataAvailablePin_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**         SetFieldBits           - void DataAvailablePin_SetFieldBits(LDD_TDeviceData *DeviceDataPtr,...
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file DataAvailablePin.c
** @version 01.08
** @brief
**         The HAL GPIO component will provide a low level API for unified
**         access to general purpose digital input/output pins across
**         various device designs.
**
**         RTOS drivers using HAL GPIO API will be simpler and more
**         portable to various microprocessors.
*/
/*!
**  @addtogroup DataAvailablePin_module DataAvailablePin module documentation
**  @{
*/

/* MODULE DataAvailablePin. */

#include "Events.h"
#include "DataAvailablePin.h"
/* MQX Lite include files */
#include "mqxlite.h"
#include "mqxlite_prv.h"
#include "IO_Map.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  LDD_RTOS_TISRVectorSettings SavedISRSettings_PortInterrupt; /* {MQXLite RTOS Adapter} Saved settings of allocated interrupt vector */
  DataAvailablePin_TPortValue EventFlags; /* Holds event flags */
  LDD_TUserData *UserData;             /* RTOS device data structure */
} DataAvailablePin_TDeviceData, *DataAvailablePin_TDeviceDataPtr; /* Device data structure type */
/* {MQXLite RTOS Adapter} Static object used for simulation of dynamic driver memory allocation */
static DataAvailablePin_TDeviceData DeviceDataPrv__DEFAULT_RTOS_ALLOC;
/*
** ===================================================================
**     Method      :  DataAvailablePin_Init (component GPIO_LDD)
*/
/*!
**     @brief
**         This method initializes the associated peripheral(s) and the
**         component internal variables. The method is called
**         automatically as a part of the application initialization
**         code.
**     @param
**         UserDataPtr     - Pointer to the RTOS device
**                           structure. This pointer will be passed to
**                           all events as parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* DataAvailablePin_Init(LDD_TUserData *UserDataPtr)
{
  /* Allocate LDD device structure */
  DataAvailablePin_TDeviceData *DeviceDataPrv;

  /* {MQXLite RTOS Adapter} Driver memory allocation: Dynamic allocation is simulated by a pointer to the static object */
  DeviceDataPrv = &DeviceDataPrv__DEFAULT_RTOS_ALLOC;
  /* Save RTOS Device structure */
  DeviceDataPrv->EventFlags = 0x00U;   /* Clears stored events */
  DeviceDataPrv->UserData = UserDataPtr; /* Store the RTOS device structure */
  /* Interrupt vector(s) allocation */
  /* {MQXLite RTOS Adapter} Save old and set new interrupt vector (function handler and ISR parameter) */
  /* Note: Exception handler for interrupt is not saved, because it is not modified */
  DeviceDataPrv->SavedISRSettings_PortInterrupt.isrData = _int_get_isr_data(LDD_ivIndex_INT_PORTC_PORTD);
  DeviceDataPrv->SavedISRSettings_PortInterrupt.isrFunction = _int_install_isr(LDD_ivIndex_INT_PORTC_PORTD, DataAvailablePin_Interrupt, DeviceDataPrv);
  /* GPIOD_PDDR: PDD&=~2 */
  GPIOD_PDDR &= (uint32_t)~(uint32_t)(GPIO_PDDR_PDD(0x02));
  /* Initialization of Port Control registers */
  /* PORTD_PCR1: ISF=0,MUX=1 */
  PORTD_PCR1 = (uint32_t)((PORTD_PCR1 & (uint32_t)~(uint32_t)(
                PORT_PCR_ISF_MASK |
                PORT_PCR_MUX(0x06)
               )) | (uint32_t)(
                PORT_PCR_MUX(0x01)
               ));
  /* NVIC_IPR7: PRI_31=0x80 */
  NVIC_IPR7 = (uint32_t)((NVIC_IPR7 & (uint32_t)~(uint32_t)(
               NVIC_IP_PRI_31(0x7F)
              )) | (uint32_t)(
               NVIC_IP_PRI_31(0x80)
              ));
  /* NVIC_ISER: SETENA|=0x80000000 */
  NVIC_ISER |= NVIC_ISER_SETENA(0x80000000);
  /* Registration of the device structure */
  PE_LDD_RegisterDeviceStructure(PE_LDD_COMPONENT_DataAvailablePin_ID,DeviceDataPrv);
  return ((LDD_TDeviceData *)DeviceDataPrv);
}

/*
** ===================================================================
**     Method      :  DataAvailablePin_SetPortEventCondition (component GPIO_LDD)
*/
/*!
**     @brief
**         This method defines condition of the [OnPortEvent] for
**         required pins of the port.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Unaligned mask of bits to setting the
**                           event condition. Each port pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected pin, bit value 1 means
**                           selected pin. The bit 0 corresponds with
**                           the pin which has index 0 within the port,
**                           the bit 1 corresponds with the pin which
**                           has index 1 within the port, etc.
**     @param
**         Condition       - Defines conditions when event
**                           is invoked. Possible values are:
**                           LDD_GPIO_DISABLED - Event doesn't invoke.
**                           LDD_GPIO_LOW - Event when logic zero.
**                           LDD_GPIO_HIGH - Event when logic one.
**                           LDD_GPIO_RISING - Event on rising edge.
**                           LDD_GPIO_FALLING - Event on falling edge.
**                           LDD_GPIO_BOTH - Event on rising and falling
**                           edge.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PARAM_MASK - Invalid pin mask.
**                           ERR_PARAM_CONDITION - Invalid condition.
*/
/* ===================================================================*/
LDD_TError DataAvailablePin_SetPortEventCondition(LDD_TDeviceData *DeviceDataPtr, DataAvailablePin_TPortValue Mask, LDD_GPIO_TEventCondition Condition)
{
  uint8_t PinIndex = 0U;

  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  /* Event mask test - this test can be disabled by setting the "Ignore range checking"
     property to the "yes" value in the "Configuration inspector" */
  if ((Mask & ((DataAvailablePin_TPortValue)(~((DataAvailablePin_TPortValue)DataAvailablePin_ALLOCATED_PINS_MASK)))) != 0U) { /* Check Mask parameter */
    return ERR_PARAM_MASK;             /* Invalid Mask parameter */
  }
  if ((Condition != LDD_GPIO_DISABLED) && (Condition != LDD_GPIO_LOW)
    && (Condition != LDD_GPIO_HIGH) && (Condition != LDD_GPIO_RISING)
    && (Condition != LDD_GPIO_FALLING) && (Condition != LDD_GPIO_BOTH)) { /* Check Condition parameter */
    return ERR_PARAM_CONDITION;        /* Invalid Condition parameter */
  }
  while (Mask != 0x00U) {
    if ((Mask & 0x01U) != 0U) {
      PORT_PDD_SetPinInterruptConfiguration(DataAvailablePin_PORTCONTROL_BASE_ADDRESS, PinIndex, Condition); /* Set pin condition */
    }
    PinIndex++;
    Mask >>= 1;
  }
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  DataAvailablePin_SetPortInputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the specified pins of the port to the input
**         direction. Only configured pins (through all of bit fields
**         in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Mask of bits to setting the input
**                           direction. Each port pin has corresponding
**                           bit in the mask. Bit value 0 means not
**                           selected bit, bit value 1 means selected
**                           bit. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
*/
/* ===================================================================*/
void DataAvailablePin_SetPortInputDirection(LDD_TDeviceData *DeviceDataPtr, DataAvailablePin_TPortValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  GPIO_PDD_SetPortInputDirectionMask(DataAvailablePin_MODULE_BASE_ADDRESS,
    ((DataAvailablePin_TPortValue)DataAvailablePin_ALLOCATED_PINS_MASK) & ((DataAvailablePin_TPortValue)(Mask)));
}

/*
** ===================================================================
**     Method      :  DataAvailablePin_SetPortOutputDirection (component GPIO_LDD)
*/
/*!
**     @brief
**         This method sets the specified pins of the port to the
**         output direction. The specified pins of the port will be
**         driven to specified states. Only configured pins (through
**         all of bit fields in this component) are affected.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Mask            - Mask of bits to setting the output
**                           direction. Each port pin has corresponding
**                           bit in the mask. Bit value 0 means not
**                           selected bit, bit value 1 means selected
**                           bit. The bit 0 corresponds with the pin
**                           which has index 0 within the port, the bit
**                           1 corresponds with the pin which has index
**                           1 within the port, etc. Only configured
**                           pins (through all of bit fields in this
**                           component) are affected.
**     @param
**         Value           - Unaligned port data value to appear on
**                           the specified port pins after they have
**                           been switched to the output direction.
*/
/* ===================================================================*/
void DataAvailablePin_SetPortOutputDirection(LDD_TDeviceData *DeviceDataPtr, DataAvailablePin_TPortValue Mask, DataAvailablePin_TPortValue Value)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  GPIO_PDD_SetPortDataOutput(DataAvailablePin_MODULE_BASE_ADDRESS,
    ((DataAvailablePin_TPortValue)(GPIO_PDD_GetPortDataOutput(DataAvailablePin_MODULE_BASE_ADDRESS)
      & ((DataAvailablePin_TPortValue)(~((DataAvailablePin_TPortValue)(((DataAvailablePin_TPortValue)DataAvailablePin_ALLOCATED_PINS_MASK)
        & ((DataAvailablePin_TPortValue)(Mask))))))))
    | (((DataAvailablePin_TPortValue)(Value))
      & ((DataAvailablePin_TPortValue)(((DataAvailablePin_TPortValue)DataAvailablePin_ALLOCATED_PINS_MASK) & ((DataAvailablePin_TPortValue)(Mask))))));
  GPIO_PDD_SetPortOutputDirectionMask(DataAvailablePin_MODULE_BASE_ADDRESS,
    ((DataAvailablePin_TPortValue)DataAvailablePin_ALLOCATED_PINS_MASK) & ((DataAvailablePin_TPortValue)(Mask)));
}

/*
** ===================================================================
**     Method      :  DataAvailablePin_GetFieldValue (component GPIO_LDD)
*/
/*!
**     @brief
**         This method returns the current input data of the specified
**         field.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to reading. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @return
**                         - Aligned current port input value masked for
**                           allocated pins of the field. The bit 0
**                           corresponds with the pin which has index 0
**                           within the given bit field, the bit 1
**                           corresponds with the pin which has index 1
**                           within the given bit field, etc.
*/
/* ===================================================================*/
DataAvailablePin_TFieldValue DataAvailablePin_GetFieldValue(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case DAP: {                        /* bit field #0 */
      return
        (DataAvailablePin_TFieldValue)(
          (
            GPIO_PDD_GetPortDataInput(DataAvailablePin_MODULE_BASE_ADDRESS)
            & (DataAvailablePin_TPortValue)DataAvailablePin_DAP_MASK
          )
          >> DataAvailablePin_DAP_START_BIT
        );
    }
    default:
      break;                           /* Invalid BitField is not treated, result is undefined */
  } /* switch (Field) */
  return (DataAvailablePin_TFieldValue)0U;
}

/*
** ===================================================================
**     Method      :  DataAvailablePin_ClearFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the inactive level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           inactive level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void DataAvailablePin_ClearFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, DataAvailablePin_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case DAP: {                        /* bit field #0 */
      GPIO_PDD_ClearPortDataOutputMask(DataAvailablePin_MODULE_BASE_ADDRESS,
        ((DataAvailablePin_TPortValue)DataAvailablePin_DAP_MASK)
        & ((DataAvailablePin_TPortValue)(Mask << DataAvailablePin_DAP_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  DataAvailablePin_SetFieldBits (component GPIO_LDD)
*/
/*!
**     @brief
**         This method drives the specified bits of the specified bit
**         field to the active level.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         Field           - Bit field to write. Bit fields are
**                           defined during design time and for each bit
**                           field there is a generated constant.
**     @param
**         Mask            - Aligned mask of bits to setting the
**                           active level. Each field pin has
**                           corresponding bit in the mask. Bit value 0
**                           means not selected bit, bit value 1 means
**                           selected bit. The bit 0 corresponds with
**                           the pin which has index 0 within the given
**                           bit field, the bit 1 corresponds with the
**                           pin which has index 1 within the given bit
**                           field, etc.
*/
/* ===================================================================*/
void DataAvailablePin_SetFieldBits(LDD_TDeviceData *DeviceDataPtr, LDD_GPIO_TBitField Field, DataAvailablePin_TFieldValue Mask)
{
  (void)DeviceDataPtr;                 /* Parameter is not used, suppress unused argument warning */
  switch (Field) {                     /* no break */
    case DAP: {                        /* bit field #0 */
      GPIO_PDD_SetPortDataOutputMask(DataAvailablePin_MODULE_BASE_ADDRESS,
        ((DataAvailablePin_TPortValue)DataAvailablePin_DAP_MASK)
        & ((DataAvailablePin_TPortValue)(Mask << DataAvailablePin_DAP_START_BIT))
      );
      break;
    }
    default:
      break;                           /* Invalid Field is not treated, result is undefined */
  } /* switch (Field) */
}

/*
** ===================================================================
**     Method      :  DataAvailablePin_Interrupt (component GPIO_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void DataAvailablePin_Interrupt(LDD_RTOS_TISRParameter _isrParameter)
{
  /* {MQXLite RTOS Adapter} ISR parameter is passed as parameter from RTOS interrupt dispatcher */
  DataAvailablePin_TDeviceDataPtr DeviceDataPrv = (DataAvailablePin_TDeviceDataPtr)_isrParameter;
  DataAvailablePin_TPortValue State;

  State = (DataAvailablePin_TPortValue)(PORT_PDD_GetInterruptFlags(DataAvailablePin_PORTCONTROL_BASE_ADDRESS)
          & ((DataAvailablePin_TPortValue)DataAvailablePin_ALLOCATED_PINS_MASK)); /* Retrieve flags */
  DeviceDataPrv->EventFlags |= State;
  PORT_PDD_ClearInterruptFlags(DataAvailablePin_PORTCONTROL_BASE_ADDRESS, State); /* Clears flags */
  DataAvailablePin_OnPortEvent(DeviceDataPrv->UserData); /* Call OnPortEvent event */
}

/* END DataAvailablePin. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
