/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : StackTimer.h
**     Project     : ProcessorExpert
**     Processor   : MKL26Z128VLL4
**     Component   : TimerUnit_LDD
**     Version     : Component 01.164, Driver 01.11, CPU db: 3.00.000
**     Compiler    : IAR ARM C Compiler
**     Date/Time   : 2014-10-10, 12:09, # CodeGen: 152
**     Abstract    :
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
**     Settings    :
**          Component name                                 : StackTimer
**          Module name                                    : TPM2
**          Counter                                        : TPM2_CNT
**          Counter direction                              : Up
**          Counter width                                  : 16 bits
**          Value type                                     : Optimal
**          Input clock source                             : Internal
**            Counter frequency                            : 187.5 kHz
**          Counter restart                                : On-overrun
**            Overrun period                               : Auto select
**            Interrupt                                    : Enabled
**              Interrupt                                  : INT_TPM2
**              Interrupt priority                         : medium priority
**          Channel list                                   : 1
**            Channel 0                                    :
**              Mode                                       : Compare
**                Compare                                  : TPM2_C0V
**                Offset                                   : 1 timer-ticks
**                Output on compare                        : Disconnect
**                Interrupt                                : Enabled
**                  Interrupt                              : INT_TPM2
**                  Interrupt priority                     : medium priority
**          Initialization                                 :
**            Enabled in init. code                        : no
**            Auto initialization                          : no
**            Event mask                                   :
**              OnCounterRestart                           : Enabled
**              OnChannel0                                 : Enabled
**              OnChannel1                                 : Disabled
**              OnChannel2                                 : Disabled
**              OnChannel3                                 : Disabled
**              OnChannel4                                 : Disabled
**              OnChannel5                                 : Disabled
**              OnChannel6                                 : Disabled
**              OnChannel7                                 : Disabled
**          CPU clock/configuration selection              :
**            Clock configuration 0                        : This component disabled
**            Clock configuration 1                        : This component enabled
**            Clock configuration 2                        : This component disabled
**            Clock configuration 3                        : This component disabled
**            Clock configuration 4                        : This component disabled
**            Clock configuration 5                        : This component disabled
**            Clock configuration 6                        : This component disabled
**            Clock configuration 7                        : This component disabled
**     Contents    :
**         Init                  - LDD_TDeviceData* StackTimer_Init(LDD_TUserData *UserDataPtr);
**         Enable                - LDD_TError StackTimer_Enable(LDD_TDeviceData *DeviceDataPtr);
**         Disable               - LDD_TError StackTimer_Disable(LDD_TDeviceData *DeviceDataPtr);
**         GetInputFrequencyReal - LDD_TimerUnit_Tfloat StackTimer_GetInputFrequencyReal(LDD_TDeviceData...
**         GetInputFrequency     - uint32_t StackTimer_GetInputFrequency(LDD_TDeviceData *DeviceDataPtr);
**         ResetCounter          - LDD_TError StackTimer_ResetCounter(LDD_TDeviceData *DeviceDataPtr);
**         GetCounterValue       - StackTimer_TValueType StackTimer_GetCounterValue(LDD_TDeviceData...
**         SetOffsetTicks        - LDD_TError StackTimer_SetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t...
**         GetOffsetTicks        - LDD_TError StackTimer_GetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t...
**
**     Copyright : 1997 - 2013 Freescale Semiconductor, Inc. All Rights Reserved.
**     SOURCE DISTRIBUTION PERMISSIBLE as directed in End User License Agreement.
**
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################*/
/*!
** @file StackTimer.h
** @version 01.11
** @brief
**          This TimerUnit component provides a low level API for unified hardware access across
**          various timer devices using the Prescaler-Counter-Compare-Capture timer structure.
*/
/*!
**  @addtogroup StackTimer_module StackTimer module documentation
**  @{
*/

#ifndef __StackTimer_H
#define __StackTimer_H

/* MODULE StackTimer. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */

#include "TPM_PDD.h"
#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif


#ifndef __BWUserType_StackTimer_TValueType
#define __BWUserType_StackTimer_TValueType
  typedef uint32_t StackTimer_TValueType ; /* Type for data parameters of methods */
#endif
#define StackTimer_CNT_INP_FREQ_U_0 0x0002DC6CUL /* Counter input frequency in Hz */
#define StackTimer_CNT_INP_FREQ_U_0_CFG_1 0x0002DC6CUL /* Counter input frequency in Hz for Clock configuration 1 */
#define StackTimer_CNT_INP_FREQ_R_0 187500.01171875076F /* Counter input frequency in Hz */
#define StackTimer_CNT_INP_FREQ_R_0_CFG_1 187500.01171875076F /* Counter input frequency in Hz for Clock configuration 1 */
#define StackTimer_CNT_INP_FREQ_COUNT 0U /* Count of predefined counter input frequencies */
#define StackTimer_PERIOD_TICKS 0x00010000UL /* Initialization value of period in 'counter ticks' */
#define StackTimer_NUMBER_OF_CHANNELS 0x01U /* Count of predefined channels */
#define StackTimer_COUNTER_WIDTH 0x10U /* Counter width in bits  */
#define StackTimer_COUNTER_DIR DIR_UP  /* Direction of counting */
#define StackTimer_OFFSET_0_TICKS 0x01ul /* Initialization value of offset as 'counter ticks' for channel 0 */
/*! Peripheral base address of a device allocated by the component. This constant can be used directly in PDD macros. */
#define StackTimer_PRPH_BASE_ADDRESS  0x4003A000U

/* Methods configuration constants - generated for all enabled component's methods */
#define StackTimer_Init_METHOD_ENABLED /*!< Init method of the component StackTimer is enabled (generated) */
#define StackTimer_Enable_METHOD_ENABLED /*!< Enable method of the component StackTimer is enabled (generated) */
#define StackTimer_Disable_METHOD_ENABLED /*!< Disable method of the component StackTimer is enabled (generated) */
#define StackTimer_GetInputFrequencyReal_METHOD_ENABLED /*!< GetInputFrequencyReal method of the component StackTimer is enabled (generated) */
#define StackTimer_GetInputFrequency_METHOD_ENABLED /*!< GetInputFrequency method of the component StackTimer is enabled (generated) */
#define StackTimer_ResetCounter_METHOD_ENABLED /*!< ResetCounter method of the component StackTimer is enabled (generated) */
#define StackTimer_GetCounterValue_METHOD_ENABLED /*!< GetCounterValue method of the component StackTimer is enabled (generated) */
#define StackTimer_SetOffsetTicks_METHOD_ENABLED /*!< SetOffsetTicks method of the component StackTimer is enabled (generated) */
#define StackTimer_GetOffsetTicks_METHOD_ENABLED /*!< GetOffsetTicks method of the component StackTimer is enabled (generated) */

/* Events configuration constants - generated for all enabled component's events */
#define StackTimer_OnCounterRestart_EVENT_ENABLED /*!< OnCounterRestart event of the component StackTimer is enabled (generated) */
#define StackTimer_OnChannel0_EVENT_ENABLED /*!< OnChannel0 event of the component StackTimer is enabled (generated) */



/*
** ===================================================================
**     Method      :  StackTimer_Init (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Initializes the device. Allocates memory for the device data
**         structure, allocates interrupt vectors and sets interrupt
**         priority, sets pin routing, sets timing, etc. If the
**         property ["Enable in init. code"] is set to "yes" value then
**         the device is also enabled (see the description of the
**         [Enable] method). In this case the [Enable] method is not
**         necessary and needn't to be generated. This method can be
**         called only once. Before the second call of Init the [Deinit]
**         must be called first.
**     @param
**         UserDataPtr     - Pointer to the user or
**                           RTOS specific data. This pointer will be
**                           passed as an event or callback parameter.
**     @return
**                         - Pointer to the dynamically allocated private
**                           structure or NULL if there was an error.
*/
/* ===================================================================*/
LDD_TDeviceData* StackTimer_Init(LDD_TUserData *UserDataPtr);

/*
** ===================================================================
**     Method      :  StackTimer_Enable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Enables the component - it starts the signal generation.
**         Events may be generated (see SetEventMask). The method is
**         not available if the counter can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError StackTimer_Enable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  StackTimer_Disable (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Disables the component - it stops signal generation and
**         events calling. The method is not available if the counter
**         can't be disabled/enabled by HW.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError StackTimer_Disable(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  StackTimer_GetInputFrequencyReal (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns current input frequency of the counter in Hz as
**         float number. This method can be used only if ["Input clock
**         source"] property is set to "internal".
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Input frequency
*/
/* ===================================================================*/
LDD_TimerUnit_Tfloat StackTimer_GetInputFrequencyReal(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  StackTimer_GetInputFrequency (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns current input frequency of the counter in Hz as
**         32-bit unsigned integer number. This method can be used only
**         if ["Input clock source"] property is set to "internal".
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Input frequency
*/
/* ===================================================================*/
uint32_t StackTimer_GetInputFrequency(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  StackTimer_ResetCounter (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Resets counter. If counter is counting up then it is set to
**         zero. If counter is counting down then counter is updated to
**         the reload value.
**         The method is not available if HW doesn't allow resetting of
**         the counter.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError StackTimer_ResetCounter(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  StackTimer_GetCounterValue (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the content of counter register. This method can be
**         used both if counter is enabled and if counter is disabled.
**         The method is not available if HW doesn't allow reading of
**         the counter.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @return
**                         - Counter value (number of counted ticks).
*/
/* ===================================================================*/
StackTimer_TValueType StackTimer_GetCounterValue(LDD_TDeviceData *DeviceDataPtr);

/*
** ===================================================================
**     Method      :  StackTimer_SetOffsetTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Sets the new offset value to channel specified by the
**         parameter ChannelIdx. It is user responsibility to use value
**         below selected period. This method is available when at
**         least one channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         Ticks           - Number of counter ticks to compare
**                           match.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range.
**                           ERR_NOTAVAIL -  The compare mode is not
**                           selected for selected channel
**                           ERR_PARAM_TICKS - Ticks parameter is out of
**                           possible range.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError StackTimer_SetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, StackTimer_TValueType Ticks);

/*
** ===================================================================
**     Method      :  StackTimer_GetOffsetTicks (component TimerUnit_LDD)
*/
/*!
**     @brief
**         Returns the number of counter ticks to compare match channel
**         specified by the parameter ChannelIdx. See also method
**         [SetOffsetTicks]. This method is available when at least one
**         channel is configured.
**     @param
**         DeviceDataPtr   - Device data structure
**                           pointer returned by [Init] method.
**     @param
**         ChannelIdx      - Index of the component
**                           channel.
**     @param
**         TicksPtr        - Pointer to return value of the
**                           number of counter ticks to compare match.
**     @return
**                         - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_PARAM_INDEX - ChannelIdx parameter is
**                           out of possible range.
**                           ERR_NOTAVAIL -  The compare mode is not
**                           selected for selected channel.
**                           ERR_SPEED - The component does not work in
**                           the active clock configuration
*/
/* ===================================================================*/
LDD_TError StackTimer_GetOffsetTicks(LDD_TDeviceData *DeviceDataPtr, uint8_t ChannelIdx, StackTimer_TValueType *TicksPtr);

/*
** ===================================================================
**     Method      :  StackTimer_SetClockConfiguration (component TimerUnit_LDD)
**
**     Description :
**         This method changes the clock configuration. During a clock
**         configuration change the component changes it's setting
**         immediately upon a request.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void StackTimer_SetClockConfiguration(LDD_TDeviceData *DeviceDataPtr, LDD_TClockConfiguration ClockConfiguration);

/*
** ===================================================================
**     Method      :  StackTimer_Interrupt (component TimerUnit_LDD)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
/* {MQXLite RTOS Adapter} ISR function prototype */
void StackTimer_Interrupt(LDD_RTOS_TISRParameter _isrParameter);

/* END StackTimer. */

#ifdef __cplusplus
}  /* extern "C" */
#endif

#endif
/* ifndef __StackTimer_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
