/********************************************
* This is a configuration file generated by 
* Processor Expert for the SecLib module.
********************************************/

#ifndef _SECLIB_CONFIG_H_
#define _SECLIB_CONFIG_H_

#ifndef gMMCAU_Support_d
#define gMMCAU_Support_d 1
#endif

#endif //_SECLIB_CONFIG_H_
