/***********************************************
* This is a configuration file generated by
* Processor Expert for the OSAbstraction module.
***********************************************/

#ifndef _OSABSTRACTION_CONFIG_H_
#define _OSABSTRACTION_CONFIG_H_

#ifndef osNumberOfSemaphores
#define osNumberOfSemaphores 5
#endif
#ifndef osNumberOfMutexes
#define osNumberOfMutexes    0
#endif
#ifndef osNumberOfTimers
#define osNumberOfTimers     0
#endif
#ifndef osNumberOfMessageQs
#define osNumberOfMessageQs  0
#endif
#ifndef osNumberOfMessages
#define osNumberOfMessages   0
#endif

#endif //_OSABSTRACTION_CONFIG_H_
