/********************************************
* This is a configuration file generated by
* Processor Expert for the LED module.
********************************************/

#ifndef _LED_CONFIG_H_
#define _LED_CONFIG_H_

#ifndef gLEDSupported_d
#define gLEDSupported_d         TRUE
#endif
#ifndef gLEDsOnTargetBoardCnt_c
#define gLEDsOnTargetBoardCnt_c 2
#endif
#ifndef gLEDBlipEnabled_d
#define gLEDBlipEnabled_d       FALSE
#endif
#ifndef mLEDInterval_c
#define mLEDInterval_c          100
#endif

#endif //_LED_CONFIG_H_
