/********************************************
* This is a configuration file generated by
* Processor Expert for the TimersManager module.
********************************************/

#ifndef _TIMERSMANAGER_CONFIG_H_
#define _TIMERSMANAGER_CONFIG_H_

#ifndef gTMR_Enabled_d
#define gTMR_Enabled_d                     TRUE
#endif
#ifndef gTimestamp_Enabled_d
#define gTimestamp_Enabled_d               TRUE
#endif
#ifndef gTMR_PIT_Timestamp_Enabled_d
#define gTMR_PIT_Timestamp_Enabled_d       FALSE
#endif
#ifndef gTMR_PIT_FreqMultipleOfMHZ_d
#define gTMR_PIT_FreqMultipleOfMHZ_d       TRUE
#endif
#ifndef TMR_TimeStampInit
#define TMR_TimeStampInit() TMR_RTCInit()
#endif
#ifndef TMR_GetTimestamp
#define TMR_GetTimestamp()  TMR_RTCGetTimestamp()
#endif
#ifndef gTMR_EnableLowPowerTimers_d
#define gTMR_EnableLowPowerTimers_d        TRUE
#endif
#ifndef gTMR_EnableMinutesSecondsTimers_d
#define gTMR_EnableMinutesSecondsTimers_d  TRUE
#endif
#ifndef gTmrApplicationTimers_c
#define gTmrApplicationTimers_c            8
#endif
#ifndef gTmrStackTimers_c
#define gTmrStackTimers_c                  10
#endif
#ifndef gTmrTaskStackSize_c
#define gTmrTaskStackSize_c                700
#endif

#endif //_TIMERSMANAGER_CONFIG_H_
