/********************************************
* This is a configuration file generated by
* Processor Expert for the Panic module.
********************************************/

#ifndef _PANIC_CONFIG_H_
#define _PANIC_CONFIG_H_

#ifndef gUsePanic_c
#define gUsePanic_c 1
#endif

#endif //_PANIC_CONFIG_H_
